general:
steps:
  gctsCloneRepository:
    host: 'http://slaa9114.btcdev.btc-ag.int:8000'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'rereifsc-gcts4'
  gctsCreateRepository:
    host: 'http://slaa9114.btcdev.btc-ag.int:8000'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'rereifsc-gcts4'
    remoteRepositoryURL: 'https://github.com/rereifsc/gCTS4'
  gctsDeploy:
    host: 'http://10:8000'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'rereifsc-gcts4'
    remoteRepositoryURL: "https://github.com/rereifsc/gCTS4"
