general:
steps:
  gctsDeploy:
    host: 'http://slaa9124.btcdev.btc-ag.int:8000'
    client: "100"
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'rereifsc-gcts4'
    remoteRepositoryURL: "https://github.com/rereifsc/gCTS4"
    verbose: true
